---
title: "Differential Methylation"
author: "Lucas Rizkalla"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: no
  html_document:
    theme: cerulean
    toc: yes
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Set up the environment
library(knitr)
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=F, tidy=T, fig.keep='high', echo=F, dpi=100, warnings=F, message=F, comment=NA, warning=F, results='as.is', fig.width = 10, fig.height = 6) #out.width=700, 
library(pander)
panderOptions('table.split.table', Inf)
set.seed(1)
library(dplyr)
options(stringsAsFactors = FALSE)
```

```{r libraries}
library (RnBeads)
library (writexl)
```

```{r settings}
# Lucas's path
data.dir           = "/Users/lucasrizkalla/Desktop/Methylation Research-VCU/Methylation850K/data"
# Mikhail's path
data.dir           = "/Users/mdozmorov/Documents/Data/VCU_work/Lathika"

runImport = TRUE
idat.dir           = file.path(data.dir, "idats")
sample.annot.abrev = file.path(data.dir, "Sample_Annot_Abrev.csv" )

fileNameOut1       = file.path(data.dir, "Differential_Methylation.xlsx")
```

# Data Import, QC, Preprocessing, and Norm

```{r}
filename = file.path(data.dir, "preprocessed_data.RData")
  
if (runImport) {
  logger.start(fname=NA)
  data.source <- c(idat.dir, sample.annot.abrev)

  rnb.set <- rnb.execute.import(data.source=data.source,
                                data.type="idat.dir")
  
  report.dir = file.path(data.dir, "AgeReport")
  unlink(report.dir, recursive = TRUE) # Delete previous report, if exists, otherwise error
  rnb.run.qc(rnb.set, report.dir)
  
  rnb.set.unfiltered <- rnb.set
  result <- rnb.run.preprocessing(rnb.set, dir.reports=report.dir)
  rnb.set.norm <- result$rnb.set
  save(list = c("rnb.set.norm"), file = filename)
} else {
  load(file = filename)
}

```

# Pairwise Analysis

```{r}
# ??? Check if the "Visits" column is factor data
# ??? The warning is still present, Invalid pairing information for column Visit . --> Treating as unpaired.
# Subset data to pairs of samples only, make sure the test runs as paired
rnb.options("differential.comparison.columns"=c("Visit"),"columns.pairing"=c("Visit"="ID"))
rnb.options("covariate.adjustment.columns"=c("Race", "Age"))

diffMeth <- rnb.execute.computeDiffMeth(rnb.set.norm, pheno.cols = "Visit")
comparison <- get.comparisons(diffMeth)[1]

get.comparisons(diffMeth)

tab.sites <- get.table(diffMeth, comparison, "sites", return.data.frame = TRUE)
tab.cpgislands <- get.table(diffMeth, comparison, "cpgislands", return.data.frame = TRUE)
tab.promoters <- get.table(diffMeth, comparison, "promoters", return.data.frame = TRUE)
tab.genes <- get.table(diffMeth, comparison, "genes", return.data.frame = TRUE)

annot.sites <- annotation(rnb.set.norm)
probe.id <- rownames(annot.sites)

# ??? Your solution works but it is fragile. A more robust and simple code below. 
# Note we 'assume' the original order is the same, but need some proof
dm.ps <- data.frame("ProbeID" = probe.id, tab.sites)
# dm.ps <- tab.sites[order(tab.sites[, "combinedRank"]), ]
dm.ps <- dm.ps[order(dm.ps$combinedRank, decreasing = FALSE), ]
which.diffmeth <- abs(dm.ps[, "mean.diff"])>0.2 & dm.ps$diffmeth.p.adj.fdr<0.05
dm.ps.cutoff <- dm.ps[which.diffmeth, ]
# dm.ps.id <- as.integer(rownames(dm.ps.cutoff))
# dm.ps.cutoff.probes <- {}
# index = 1
# while (index < length(dm.ps.id) + 1){
#   dm.ps.cutoff.probes[index] = probe.id[dm.ps.id[index]]
#   index = index + 1
# }
# dm.ps.cutoff <- dm.ps.cutoff %>% add_column("ProbeID" = dm.ps.cutoff.probes, .before = "mean.g1")

# ??? Row IDs will be different for CpG islands, promoters, genes. Find out shich ones.
# Should be the same number of rows as the corresponding object
# Probe IDs cannot be used, they are for individual probes. The below errors
dm.cpgs <- data.frame("ProbeID" = probe.id, tab.cpgislands)
nrow(tab.cpgislands) # Find annotation with this number of rows
length(probe.id)

dm.cpgs <- tab.cpgislands[order(tab.cpgislands[, "combinedRank"]),]
dm.cpgs.id <- as.integer(rownames(dm.cpgs))
dm.cpgs.probes <- {}
index = 1
while (index < length(dm.cpgs.id) + 1){
  dm.cpgs.probes[index] = probe.id[dm.ps.id[index]]
  index = index + 1
}
dm.cpgs <- dm.cpgs %>% add_column("ProbeID" = dm.cpgs.probes, .before = "mean.mean.g1")

dm.proms <- tab.promoters[order(tab.promoters[, "combinedRank"]),]
dm.proms.id <- as.integer(rownames(dm.proms))
dm.proms.probes <- {}
index = 1
while (index < length(dm.proms.id) + 1){
  dm.proms.probes[index] = probe.id[dm.proms.id[index]]
  index = index + 1
}
dm.proms <- dm.proms %>% add_column("ProbeID" = dm.proms.probes, .before = "mean.mean.g1")

dm.gs <- tab.genes[order(tab.genes[, "combinedRank"]),]
dm.gs.id <- as.integer(rownames(dm.gs))
dm.gs.probes <- {}
index = 1
while (index < length(dm.gs.id) + 1){
  dm.gs.probes[index] = probe.id[dm.gs.id[index]]
  index = index + 1
}
dm.gs <- dm.gs %>% add_column("ProbeID" = dm.gs.probes, .before = "mean.mean.g1")

# Save all results
# Note the full results make ~200Mb xlsx
x <- list(dm.ps.cutoff, dm.cpgs, dm.proms, dm.gs) 
names(x) <- c("Sites", "Cpgs", "Promoters", "Genes")
write_xlsx(x, path = fileNameOut1)
```

#Enrichment Analysis

```{r}
rnb.options("differential.enrichment.go"=TRUE)
rnb.options("differential.enrichment.lola"=TRUE)

# ??? Info message to look into: Not annotated with entrezID --> Skipped
enrich.go <- performGoEnrichment.diffMeth(rnb.set.norm, diffMeth, verbose=TRUE)

# ??? Why those parameters were used for subsetting? What are other options that may be informative? Why they were not selected?
enrich.table.go <- enrich.go[["region"]][[comparison]][["BP"]][["promoters"]][["rankCut_500"]][["hypo"]]
summary(enrich.table.go)

# ??? Same with LOLA analysis - what informative results we can get from there?
lolaDest <- tempfile()
dir.create(lolaDest)
lolaDirs <- downloadLolaDbs(lolaDest, dbs="LOLACore")
```


```{r session_info}
xfun::session_info()
```
