---
title: "Annotation Setup"
author: "Lucas Rizkalla"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: cerulean
    toc: yes
  pdf_document:
    toc: no
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Set up the environment
library(knitr)
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=F, tidy=T, fig.keep='high', echo=F, dpi=100, warnings=F, message=F, comment=NA, warning=F, results='as.is', fig.width = 10, fig.height = 6) #out.width=700, 
library(pander)
panderOptions('table.split.table', Inf)
set.seed(1)
library(dplyr)
options(stringsAsFactors = FALSE)
```

```{r libraries}
library(gdata)
```

```{r settings}
# Lukas's path
data.dir           = "/Users/lucasrizkalla/Desktop/Methylation Research-VCU/Methylation850K/data"
# Mikhail's path
data.dir           = "/Users/mdozmorov/Documents/Work/GitHub/Methylation850K/data"
# Annotation files
sample.annotation  = file.path(data.dir, "Sample_Annotation.xlsx")
description2sample = file.path(data.dir, "library_ids_haib20TS6106.csv")
sample2idat        = file.path(data.dir, "Sample_Table.csv")
```

#Creation of a Sample Annotation file that matches IDs of Idat files

```{r}
myIdatName   = read.csv(sample2idat)
myIdentifier = read.csv(description2sample)
myAnnotation = read.xls(sample.annotation)

# Subset to common IDs
common_id    <- intersect(myAnnotation$Identifier, myIdentifier$Description)
myIdentifier <- myIdentifier[myIdentifier$Description %in% common_id, ]
myIdatName   <- myIdatName[myIdatName$Sample %in% myIdentifier$Sample.Name, ]

#Remove extra columns
myAnnotation <- myAnnotation[-c(41:125)]
#Create new column to be used as idat file name (SentrixID_SentrixPosition)
myIdatName$barcode = paste(myIdatName$BeadChip, "_", myIdatName$SSR, myIdatName$SSC, sep = "")
#Sort by SampleName in order to cross reference with Sample in myIdatName (should be identical in order)
# This seems like a bug. all.equal test fails 
# myIdentifier = myIdentifier[order(myIdentifier$Sample.Name), ] # Had to add "."
# all.equal(myIdentifier$Sample.Name, myIdatName$Sample)
myIdentifier <- myIdentifier[match(myIdatName$Sample, myIdentifier$Sample.Name), ]
all.equal(myIdentifier$Sample.Name, myIdatName$Sample) # TRUE if order matches
#Replace column with corresponding IDs that will be found in myAnnotation 
myIdatName$Sample <- myIdentifier$Description

#Sort in numerical order so that it correspond correctly to myAnnotation
myIdatName = myIdatName[order(myIdatName$Sample), ]
#Once sorted, replaced with correct Idat file name
myAnnotation$Identifier <- myIdatName$barcode
#Set column name to "barcode"
names(myAnnotation)[names(myAnnotation) == "Identifier"] <- "barcode"

mySampleAnnotation <- write.csv(myAnnotation, file = file.path(data.dir, "Sample_Annotation.csv"))
```


```{r session_info}
xfun::session_info()
```
